#FROM openjdk:21
FROM public.ecr.aws/amazoncorretto/amazoncorretto:21
ARG JAR_FILE=target/*.jar
ARG AWS_SECRETS_PATH
ENV aws.secret.path=${AWS_SECRETS_PATH}
COPY ${JAR_FILE} app.jar
ENTRYPOINT ["java","-jar","app.jar"]