CREATE TABLE CARD_SUBORDER_ITEM_GRADE (
    card_suborder_item_grade_id int8 PRIMARY KEY,
    back_img_url VARCHAR2(255),
    front_img_url VARCHAR(255),
    certificate_lookup_no VARCHAR(255),
    is_graded BPCHAR(1) DEFAULT 'N' CHECK (is_graded IN ('Y', 'N')),
    jr_grader VARCHAR(100),
    jr_graded_date TIMESTAMP,
    jr_grader_comment VARCHAR(255),
    jr_centering_val int4,
    jr_corners_val int4,
    jr_edges_val int4,
    jr_surface_val int4,
    jr_auto_val int4,
    jr_final_grade_val int4,
    jr_min_grade int4,
    jr_is_black_label BPCHAR(1) DEFAULT 'N' CHECK (jr_is_black_label IN ('Y', 'N')),
    sr_grader VARCHAR(100),
    sr_graded_date TIMESTAMP,
    sr_grader_comment VARCHAR(255),
    sr_centering_val int4,
    sr_corners_val int4,
    sr_edges_val int4,
    sr_surface_val int4,
    sr_auto_val int4,
    sr_final_grade_val int4,
    sr_min_grade int4,
    sr_is_black_label BPCHAR(1) DEFAULT 'N' CHECK (sr_is_black_label IN ('Y', 'N')),
    is_subgrade BPCHAR(1) DEFAULT 'N' CHECK (is_subgrade IN ('Y', 'N')),
    grade_type VARCHAR(100),
    is_second_review BPCHAR(1) DEFAULT 'N' CHECK (is_second_review IN ('Y', 'N')),
    is_senior_agree BPCHAR(1) DEFAULT 'N' CHECK (is_senior_agree IN ('Y', 'N')),
    is_cant_grade BPCHAR(1) DEFAULT 'N' CHECK (is_cant_grade IN ('Y', 'N')),
    cant_grade_reason VARCHAR(500),
    is_deactivated BPCHAR(1) DEFAULT 'N' CHECK (is_deactivated IN ('Y', 'N')),
    is_svc_unavailable BPCHAR(1) DEFAULT 'N' CHECK (is_svc_unavailable IN ('Y', 'N')),
    svc_unavailable_comments VARCHAR(255),
    img_url VARCHAR(200),
    card_suborder_item_id int8 NOT NULL,
    CONSTRAINT FK_CARD_SUBORDER_ITEM FOREIGN KEY (card_suborder_item_id)
        REFERENCES CARD_SUBORDER_ITEM (card_suborder_item_id)
);
CREATE SEQUENCE ORDERS.CARD_SUBORDER_ITEM_GRADE_ID_SEQ START WITH 1 INCREMENT BY 1;
CREATE TABLE CARD_SUBORDER_ITEM_GRADE_ISSUES (
    card_suborder_item_grade_issues_id int8 PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    card_suborder_item_id int8,
    category VARCHAR(255) NOT NULL,
    sub_category VARCHAR(255) NOT NULL,
    is_still_applicable BPCHAR(1) DEFAULT 'N' NOT NULL CHECK (is_still_applicable IN ('Y', 'N')),
    is_active BPCHAR(1) DEFAULT 'Y' NOT NULL CHECK (is_active IN ('Y', 'N')),
    is_deleted BPCHAR(1) DEFAULT 'N' NOT NULL CHECK (is_deleted IN ('Y', 'N')),
    CONSTRAINT FK_CARD_SUBORDER_ITEM_ISSUES FOREIGN KEY (card_suborder_item_id)
        REFERENCES CARD_SUBORDER_ITEM (card_suborder_item_id)
);
ALTER TABLE orders.card_suborder_job ADD grader int8 NULL;
ALTER TABLE orders.card_suborder_item_grade ADD CONSTRAINT card_suborder_item_grade_fk FOREIGN KEY (grader) REFERENCES users.users(user_id);
ALTER TABLE orders.card_suborder_job ADD grading_status varchar(255) NULL;

